apiVersion: v1
kind: Service
metadata:
  name: nginx-backend-service
spec:
  type: NodePort
  selector:
    app: python-back
    type: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-group
  labels:
    app: python-back
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-back
      type: backend
  template:
    metadata:
      labels:
        app: python-back
        type: backend
    spec:
     containers:
        - name: backend-webserver
          image: nukezzz101/backend_server:0.6
---
apiVersion: v1
kind: Service
metadata:
  name: front-web-server-service
spec:
  type: NodePort
  selector:
    app: nginx-app
    type: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-group
  labels:
    app: nginx-app
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
      type: frontend
  template:
    metadata:
      labels:
        app: nginx-app
        type: frontend
    spec:
      containers:
        - name: frontend-webserver
          image: nukezzz101/frontend_server:0.2
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongodb
    type: database
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment-group
  labels:
    app: mongodb
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      type: database
  template:
    metadata:
      labels:
        app: mongodb
        type: database
    spec:
      containers:
        - name: database-mongo
          image: nukezzz101/mongo:4.0.27-xenial
---
