apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dg-listall
  labels:
    app: Listall
    type: backendAPI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Listall
      type: backendAPI
  template:
    metadata:
      labels:
        app: Listall
        type: backendAPI
    spec:
      containers:
        - name: listall
          image: nukezzz101/listall:0.5
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-cred
                  key: MONGODB_URI