apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dg-viewcountry
  labels:
    app: Viewcountry
    type: backendAPI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Viewcountry
      type: backendAPI
  template:
    metadata:
      labels:
        app: Viewcountry
        type: backendAPI
    spec:
      containers:
        - name: viewcountry
          image: nukezzz101/viewcountry:0.5
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-cred
                  key: MONGODB_URI