apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo
    type: database
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: mongo-container
      image: mongo:5.0-focal
      ports:
        - containerPort: 27017
          name: "data-port"
      volumeMounts:
        - mountPath: "/data/db"
          name: pv-storage