name: test
on:
  push:
    branches: [ main ]
jobs:
  job01:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: print date
      run: Get-Date
  job02:
    runs-on: ubuntu-latest
    steps:
    - name: print date
      run: date
  job03:
    needs: [ job01,job02 ]
    runs-on: ubuntu-latest
    steps:
    - name: print date
      run: date

